spring.application.name=billeteravirtual
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false
spring.web.resources.chain.enabled=false
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=billeteravirtualaj@gmail.com
spring.mail.password=sarq htpo eujp ajgn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=phi3